name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt install libxtst-dev
    - name: Setup headless environment
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: Build
      run: RUST_BACKTRACE=1 cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
