name: build

on: [push, pull-request]

jobs:
  build:

    runs-on: ${{matrix.os}}
    env:
      DISPLAY: ':99'
    strategy:
      fail-fast: false
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          headless: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - os: ubuntu-latest
          dependencies: sudo apt install libxtst-dev

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: ${{matrix.dependencies}}
    - name: Setup headless environment
      run: ${{matrix.headless}}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Linter
      run: cargo clippy --verbose
